config:
  loader:
    articleIdentifierPrefix: "urn:nytimes:article:"
    categoryIdentifierPrefix: "urn:nytimes:cat:"
    authorIdentifierPrefix: "urn:nytimes:author:"
    resourceUriPrefix: "https://rss.nytimes.com/services/xml/rss/nyt/"
  sources:
    - "World"
    - "Africa"
  s3:
    bucket: "2025-news-feed"
